// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace nogtstapi.Models;

public partial class Customer
{
    public string Name { get; set; }

    public int? CustomerNumber { get; set; }

    public int Id { get; set; }

    public bool? IsDeleted { get; set; }

    public DateTime? Created { get; set; }
}